name: My Test workflow

on: [push]

jobs:
    say-hello:
      runs-on: ubuntu-latest
      steps:
        - name: Say hello
          run: echo "Hello, Github actions!"


    needs: [say-hello]
    runs-on: ubuntu-latest
    steps:

      - name: Check out this repo 
        uses: actions/checkout@v6

      - name: Install dependencies 
        run: sudo apt install -y build-essential python3 

      - run: pwd

      - name: Run test 
        run: python3 test.py 
